version: "3.9"

services:
  # ================== NGINX ==================
  nginx-gateway:
    image: nginx:alpine
    container_name: mechat-nginx-gateway-dev
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mechat-api
      - mechat-consumer
    networks: [mechat-dev-net]

  # ================== API ==================
  mechat-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mechat-api-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    expose:
      - "5000"
    depends_on:
      - mssql
      - redis
      - rabbitmq
    networks: [mechat-dev-net]

  mechat-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: mechat-consumer-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development    
    expose:
      - "5001"
    depends_on:
      - rabbitmq
      - redis
    networks: [mechat-dev-net]

  # ================== MSSQL ==================
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mechat-mssql-dev
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MeChat@2024"
    ports:
      - "1433:1433"
    volumes:
      - mssql_dev_data:/var/opt/mssql
    networks:
      - mechat-dev-net

  # ================== REDIS ==================
  redis:
    image: redis:7
    container_name: mechat-redis-dev
    command: redis-server --requirepass mechat
    ports:
      - "6379:6379"
    networks:
      - mechat-dev-net

  # ================== RABBITMQ ==================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mechat-rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: me-chat
    networks:
      - mechat-dev-net

# ================== VOLUMES ==================
volumes:
  mssql_dev_data:

# ================== NETWORK ==================
networks:
  mechat-dev-net:
    driver: bridge
