FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY MeChat.sln ./
COPY src ./src
COPY test ./test

RUN dotnet restore MeChat.sln
RUN dotnet publish "src/MeChat.Infrastructure.MessageBroker.Consumer/MeChat.Infrastructure.MessageBroker.Consumer.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet","MeChat.Infrastructure.MessageBroker.Consumer.dll"]
