name: MeChat CI/CD

on:
  push:
    branches:
      - main   

jobs:
  build:
    name: Build Projects
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install .NET SDK version 7.0
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Publish API (only on main branch)
      - name: Publish MeChat.API (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          ASPNETCORE_ENVIRONMENT=Production dotnet publish src/MeChat.API/MeChat.API.csproj -c Release -o ./publish-api

      # Publish Consumer (only on main branch)
      - name: Publish MessageBroker.Consumer (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          ASPNETCORE_ENVIRONMENT=Production dotnet publish src/MeChat.Infrastructure.MessageBroker.Consumer/MeChat.Infrastructure.MessageBroker.Consumer.csproj -c Release -o ./publish-consumer

      # Upload API artifact
      - name: Upload API artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: publish-api
          path: ./publish-api

      # Upload Consumer artifact
      - name: Upload Consumer artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: publish-consumer
          path: ./publish-consumer

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      # Restore test project
      - name: Restore MeChat.Architecture.Tests
        run: dotnet restore test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj

      # Build test project
      - name: Build MeChat.Architecture.Tests
        run: dotnet build test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj --no-restore --configuration Release

      # Run tests
      - name: Run MeChat.Architecture.Tests
        run: dotnet test test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj --no-build --configuration Release --logger "trx"

  deploy:
    name: Deploy to IIS Server
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    needs: test

    steps:
      # Download API artifact
      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-api
          path: publish-api

      # Download Consumer artifact
      - name: Download Consumer artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-consumer
          path: publish-consumer

      # Deploy using WinRM
      - name: Deploy via WinRM
        shell: powershell
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
          VM_DEPLOY_FOLDER: ${{ secrets.VM_DEPLOY_FOLDER }}
          VM_DEPLOY_CONSUMER_FOLDER: ${{ secrets.VM_DEPLOY_CONSUMER_FOLDER }}
          VM_CONSUMER_SERVICE: ${{ secrets.VM_CONSUMER_SERVICE }}
        run: |
          Write-Host "=== Configuring WinRM client ==="
          Set-Item WSMan:\localhost\Client\AllowUnencrypted -Value $true
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "$env:VM_HOST" -Force
          Set-Item WSMan:\localhost\Client\Auth\Basic -Value $true

          Write-Host "=== Creating credential object ==="
          $secpasswd = ConvertTo-SecureString "$env:VM_PASSWORD" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($env:VM_USERNAME, $secpasswd)

          Write-Host "=== Opening remote session to $env:VM_HOST ==="
          $session = New-PSSession -ComputerName $env:VM_HOST -Credential $cred -Authentication Basic

          Write-Host "=== Stopping IIS and Consumer service if running ==="
          Invoke-Command -Session $session -ScriptBlock {
            param($serviceName)
            iisreset /stop
            $svc = Get-Service $serviceName -ErrorAction SilentlyContinue
            if ($svc -and $svc.Status -eq 'Running') {
              Stop-Service $serviceName -Force
            }
          } -ArgumentList $env:VM_CONSUMER_SERVICE

          Write-Host "=== Ensuring deploy folders exist ==="
          Invoke-Command -Session $session -ScriptBlock {
            param($path1, $path2)
            New-Item -Path $path1 -ItemType Directory -Force | Out-Null
            New-Item -Path $path2 -ItemType Directory -Force | Out-Null
          } -ArgumentList $env:VM_DEPLOY_FOLDER, $env:VM_DEPLOY_CONSUMER_FOLDER

          Write-Host "=== Copying API files ==="
          Copy-Item -Path ".\publish-api\*" -Destination $env:VM_DEPLOY_FOLDER -Recurse -Force -ToSession $session -ErrorAction Stop

          Write-Host "=== Copying Consumer files ==="
          Copy-Item -Path ".\publish-consumer\*" -Destination $env:VM_DEPLOY_CONSUMER_FOLDER -Recurse -Force -ToSession $session -ErrorAction Stop

          Write-Host "=== Restarting IIS and Consumer service ==="
          Invoke-Command -Session $session -ScriptBlock {
            param($serviceName)
            iisreset /start
            $svc = Get-Service $serviceName -ErrorAction SilentlyContinue
            if ($svc -and $svc.Status -ne 'Running') {
              Start-Service $serviceName -ErrorAction Stop
            }
          } -ArgumentList $env:VM_CONSUMER_SERVICE

          Write-Host "=== Closing remote session ==="
          Remove-PSSession $session
