name: .NET Core CI - Run Tests for MeChat.Architecture.Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET Core SDK
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Set to your .NET version

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the solution
    - name: Build the solution
      run: dotnet build --configuration Release

    # Run unit tests for the specific test project
    - name: Run unit tests for MeChat.Architecture.Tests
      run: dotnet test test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj --no-build --verbosity normal
